### ISSUE TITLE
inicio de sesion

### ISSUE THREAD

**Issue by ulises58** [phpcfdi/cfdi-sat-scraper#35]
@eclipxe13 no soy muy bueno en php pero ahi alguna forma de poder "inicio de sesion" sin hacer query ?
ha lo que me refiero es que si ahi manera de hacer que primero yo sepa si las credenciales que ingrese son las correctas para que ya en base a esto despues que se genere el json con la sesion yo pueda hacer los querys para traer la informacion.

**Comment by eclipxe13** [comment]
Para eviat malos entendidos se trata de poder autenticarse en el portal de CFDI, pero sin consumir nada. ¿cierto?

Se puede hacer con el método `SatScraper::confirmSessionIsAlive()`, si la confirmación es negativa generará una excepción. Si es positiva no pasará nada.

La clase `SessionManager` (`@internal`, no la uses porque puede cambiar sin previo aviso) tiene el manejo de la sesión y te podría ayudar a entender cómo se comporta.

**Comment by eclipxe13** [comment]
Estoy pensando en agregar esto al `README`:

El siguiente ejemplo muestra cómo usar el método `confirmSessionIsAlive` para verificar que los datos de sesión son correctos. El funcionamiento interno del scraper es: Si la sesión no se inicializó previamente entonces se intentará hacer el proceso de autenticación, además se verificará que la sesión siga vigente. 

```php
<?php declare(strict_types=1);

use PhpCfdi\CfdiSatScraper\Contracts\CaptchaResolverInterface;
use PhpCfdi\CfdiSatScraper\Exceptions\LoginException;
use PhpCfdi\CfdiSatScraper\SatScraper;
use PhpCfdi\CfdiSatScraper\SatSessionData;

/** @var CaptchaResolverInterface $captchaResolver */
$satScraper = new SatScraper(new SatSessionData('rfc', 'ciec', $captchaResolver));
try {
    $satScraper->confirmSessionIsAlive();
} catch (LoginException $exception) {
    echo 'ERROR: ', $exception->getMessage(), PHP_EOL;
    return;
}
```

@blacktrue @ulises58 qué opinan ?

**Comment by blacktrue** [comment]
Totalmente de acuerdo, mi propuesta iba ser usar` SessionManager` pero analizando bien, tu propuesta es mejor @eclipxe13

**Comment by ulises58** [comment]
@eclipxe13  Exactamente eso es lo que estaba buscando y me parece perfecto que lo agregues en el readme.
En mi caso no tenia muy claro lo que les comente.
Muchas gracias por su respuesta (estoy empezando en los temas del sat y pues desarrollo con php)
