### ISSUE TITLE
Inicio de sesión por medio de la eFirma

### ISSUE THREAD

**Issue by TheSpectroMx** [phpcfdi/cfdi-sat-scraper#39]
¿Hay posibilidad en futuras versiones el iniciar sesion por medio de la efirma?

**Comment by fernas** [comment]
¿Se está desarrollando una solución para esto?

**Comment by eclipxe13** [comment]
Yo hice una prueba de concepto, pero no funcionó de manera estable.
Este proyecto está abierto a contribuciones, si alguien tiene alguna oportunidad de desarrollarlo podría aceptarse el Pull Request.
