### ISSUE TITLE
CFDIs de Retencion e Información de pagos

### ISSUE THREAD

**Issue by TheSpectroMx** [phpcfdi/cfdi-sat-scraper#40]
¿Podría en un futuro como mejora consumir los mismos servicios pero con los CFDIs de Retencion e Información de pagos? La URL para consultar dichos CFDIs es: https://prodretencioncontribuyente.clouda.sat.gob.mx/

**Comment by eclipxe13** [comment]
No se implementará en esta versión, es probable que, si se llegara a implementar, sea en su propio proyecto.
