### ISSUE TITLE
PREGUNTA

### ISSUE THREAD

**Issue by jorge-koki** [phpcfdi/cfdi-sat-scraper#41]
Alguien sabe si existe algun web service , libreria o algo para consultar en la lista negra del SAT y saber si se encuentra el 
 RFC?

**Comment by TheSpectroMx** [comment]
Hola @jorge-koki puedes usar el del estado de CFDI, actualizaron el servicio si no mal recuerdo en diciembre y ya te trae código 100 y 200.... puedes usar https://github.com/phpcfdi/sat-estado-cfdi-soap ojo solo te dice si esta en la lista, no te da el estado.... saludos

**Comment by adolfoflores** [comment]
> Alguien sabe si existe algun web service , libreria o algo para consultar en la lista negra del SAT y saber si se encuentra el
> RFC?

ninja.cfdi tiene el servicio, pero se me hizo algo caro, y tienes que llamar para cotizar.

**Comment by TheSpectroMx** [comment]
O podrías descargar la lista que pone el SAT y ya hacer tu implementación a tu gusto

**Comment by eclipxe13** [comment]
@jorge-koki está dentro de los proyectos de phpCfdi contar con un recurso en GitHub alimentado constantemente con las actualizaciones del SAT. Sin embargo aun no lo tenemos.

Como dice @TheSpectroMx, si consultas el estado de un CFDI te dirá si el Emisor está en la lista de EFOS.

@adolfoflores No había visto el servicio que mencionaste, entré pero no tiene la consulta de EFOS, lo que revisa es la lista de LINC RFC.

PD: Voy a cerrar este issue debido a que no tiene relación con esta librería. Sin embargo, te invito a platicar con la comunidad de PhpCfdi en Discord <https://discord.gg/aFGYXvX>, donde abordamos temas como el que mencionaste.

**Comment by joneldiablo** [comment]
por acá descargamos el archivo http://omawww.sat.gob.mx/cifras_sat/Documents/Listado_Completo_69-B.csv que puedes consultar en http://omawww.sat.gob.mx/cifras_sat/Paginas/datos/vinculo.html?page=ListCompleta69B.html  después elimino todo en la tabla de mi base de datos  y vuelvo a cargar la información con el contenido del csv
