### ISSUE TITLE
[PREGUNTA] cómo optienen la cookie de autenticación?

### ISSUE THREAD

**Issue by joneldiablo** [phpcfdi/cfdi-sat-scraper#42]
Hola buen día, estoy creando un proyecto en nodejs para hacer más o menos lo mismo que este proyecto, quiero mostrarle al usuario una cuadro donde ingrese sus datos de rfc, contraseña y que meta el valor de la captcha, eso ya lo logré y le mando al sat todos los datos, pero hay un redireccionamiento a `https://portalcfdi.facturaelectronica.sat.gob.mx` que trae un form que con javascript automaticamente se hacen un submit, en el form tienen tres campos ocultos (`<input type="hidden"/>`)  *wa*, *wresult* y *wctx*. wresult trae como valor xml completito que es como una respuesta de SOAP que creo que es la solicitud de token. justo ahí estoy atorado porque al hacer la solicitud "igualita" por medio de post, no me devuelve la cookie de autenticación, quería preguntarles cómo resolvieron el acceso y si voy bien o mal ..... o.O

**Comment by eclipxe13** [comment]
En toda la comunicación usamos un cliente con un Cookie Jar y que va guardando todas las cookies que van dejando los sitios del SAT.

Efectivamente, en el camino hay redireccionamientos, formularios que se auto envían y cosas así. Y el portal es una página con tecnología ASPX en donde también hay que ser muy cuidadosos con la información que se envía y recibe.

Yo te recomendaría entrar por el navegador grabar toda la conversación HTTP. De esa forma notarás los pasos obligatorios y opcionales. Tanto para hacer el registro como para cerrar la sesión.

Otra buena idea es -en lugar de hacer un scrap de bajo nivel con mensajes HTTP- hacer un scrap de "alto nivel" utilizando la automatización del navegador (tipo puppeteer) y así tendrías menos pasos que automatizar y en una de esas hasta podrías permitir la autenticación vía FIEL, saltando de esta manera el CAPTCHA.

**Comment by joneldiablo** [comment]
Hola eclipxe13 gracias por tu respuesta. Ya lo logré, en nodeJS hay un proyecto que se llama phantomJS creo que es similar a puppeteer con eso logré hacer la conexión usando la captcha como primer paso, luego voy guardando las cookies, más o menos como mencionas logré hacerlo, gracias!
