### ISSUE TITLE
Client error: `GET https://cfdiau.sat.gob.mx/nidp/jcaptcha.jpg` resulted in a `404 Not Found`

### ISSUE THREAD

**Issue by ulises58** [phpcfdi/cfdi-sat-scraper#5]
No encuntro como solucionar esto

**Comment by jbatun21564065** [comment]
Recuerda que http es un protocolo sin estado.

Para este fin, es obvio que se usan técnicas como el de los ### headers y eso.
Si deseas así nada más obtener del jpg a la primera, con un ### request http, no creo, debes analizar el###  request previo con alguna herramienta, que te analice el código de la **solicitud HTTP**, te recomiendo el _**### BURP SUITE.**_

**Comment by eclipxe13** [comment]
@ulises58 la página del SAT cambió y ahora usa el captcha en una imagen embedida, la versión develop ya tiene solucionado el problema y la versión master pronto será actualizada con estos cambios

**Comment by ulises58** [comment]
@eclipxe13 muchas gracias
