### ISSUE TITLE
2 mil facturas por dia

### ISSUE THREAD

**Issue by ccastillo-contalink** [phpcfdi/cfdi-sat-scraper#73]
Hola 

Es posible sacar mas de 2 mil facturas por dia, es que si entro a sesion desde la pagina web, solo me deja descargar 2 mil facturas.

**Comment by ccastillo-contalink** [comment]
hola @TheSpectroMx no se puede engañar a la SAT de algiuna manera?

**Comment by eclipxe13** [comment]
Sí y no. El control lo lleva por RFC por día, desde el servidor. Lo que hemos detectado es que a veces se rebasa el límite usando una alta concurrencia. Como si sucediera un race-condition al momento de actualizar su contador de descargas.

**Comment by ccastillo-contalink** [comment]
@eclipxe13 en tu experiencia, cual seria la concurrencia ideal para sobrepasar mas de 2000 descargas
muchas gracias, felicidades por compartir el proyecto.

**Comment by eclipxe13** [comment]
:shrug: depende de los recursos en tu máquina (para poner un número alto), de la conexión (para poder hacer múltiples ejecuciones sin problemas) y de la saturación que exista en el SAT (entre menos saturado, más fácil podrá manejar el contador). Creo que tendrás que hacer pruebas empezando con 10.

Creo que estos temas que no son un issue en la herramienta, si no consejos de implementación, los podrías tratar con otros miembros de la comunidad: https://discord.gg/aFGYXvX (canal `#cfdi-sat-scraper`).
