### ISSUE TITLE
Version para PHP 5.4

### ISSUE THREAD

**Issue by nmovazquez** [phpcfdi/cfdi-sat-scraper#80]
Muy buena libreria, quería saber si se tiene alguna versión para PHP 5.4 o como podría implementarla para esa versión de php? Saludos.

**Comment by blacktrue** [comment]
Hola @nmovazquez

Que bueno que te gustó la librería, lamentablemente la versión de PHP 5.4 ya está deprecada y no tiene soporte por parte del equipo de PHP, te recomendamos encarecidamente actualizar a la última versión con soporte activo.

Nuestra librería es compatible únicamente con la última versión con soporte activo, aquí dejo los detalles.
https://github.com/phpcfdi/cfdi-sat-scraper#compatibilidad
